version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.56
    ports:
      - "4318:4318"  # OpenTelemetry Collector (OTLP) endpoint
      - "16686:16686" # Jaeger UI
    container_name: jaeger
